export const graphData = {
  nodes: [
    { id: 'set-in_',       label: '\\text{Set}, \\in' },
    { id: 'setminus',      label: '\\setminus' },
    { id: 'subset_',       label: '\\subset' },
    { id: 'nothing_',      label: '\\varnothing' },
    { id: 'set-equality',  label: '=' },
    { id: 'pair',          label: 'Пара' },
    { id: 'function',      label: 'Отображение' },
    { id: 'family',        label: 'Семейство' },
    { id: 'cap-cup',       label: '\\cap, \\cup' },
    { id: 'field-ax',      label: 'Аксиомы\nполя' },
    { id: 'order-ax',      label: 'Аксиомы\nпорядка' },
    { id: 'morgan-laws',   label: 'Законы\nде Моргана' },
    { id: 'distr-cap-cup', label: '\\text{Distributive property of } \\cap \\text{and } \\cup' },
    { id: 'intervals',     label: '[], (), \\langle \\rangle, \\pm \\infty' },
    { id: 'ordinals',      label: 'Ординалы' },
    { id: 'archimed-ax',   label: 'Аксиома\nАрхимеда' },
    { id: 'cantor-ax',     label: 'Аксиома\nКантора' },
    { id: 'r',             label: '\\mathbb{R}' },
    { id: 'abs',           label: '|\\cdot|' },
    { id: 'inductive-set', label: 'Индуктивное\nмножество' },
    { id: 'n',             label: '\\mathbb{N}' },
    { id: 'sequence',      label: 'Последовательность' },
    { id: 'z-q',           label: '\\mathbb{Z}, \\mathbb{Q}' },
    { id: 'times-rel',     label: '\\times, \\text{relation}' },
    { id: 'bounds',        label: 'Ограниченность,\nграница' },
    { id: 'max-min',       label: '\\max, \\min' },
    { id: 'floor',         label: '[\\ \\cdot\\ ]' },
    { id: 'r-func',        label: 'Функция' },
    { id: 'img-preimg',    label: 'Образ, прообраз' },
    { id: 'inj-surj-bij',  label: 'Cюръекция,\nинъекция, биекция' },
    { id: 'inverse-func',  label: 'Обратное\nотображение' },
    { id: 'composition',   label: '\\text{Composition, id}' },
    { id: 'equiv-rel',     label: 'Отношение\nэквивалентности' },
    { id: 'equinum',       label: 'Равномощность' },
    { id: 'count',         label: 'Счётность' },
    { id: 'math-induct',   label: 'Принцип мат.\nиндукции' },
    { id: 'binomial-th',   label: 'Бином\nНьютона' },
    { id: 'finite-min',    label: '\\exists \\max \\text{and}\\, \\min \\text{in finite set}' },
    { id: 'q-dense',       label: '\\text{Density of } \\mathbb{Q}' },
    { id: 'ex-count-sub',  label: '\\forall \\text{inf. set} \\supset \\text{count. subset}' },
    { id: 'inf-sub-count', label: '\\forall \\text{inf. subset of count. subset} - \\text{count.}' },
    { id: 'count-union',   label: '\\bigcup\\limits_{\\text{count.}} \\text{count.} - \\text{count.}' },
    { id: 'q-count',       label: '\\mathbb{Q} - \\text{count.}' },
    { id: 'r-continuum',   label: '[0, 1] - \\text{not count.}' }
  ],
  edges: [
    { from: 'nothing_', to: ['set-in_'] },
    { from: 'subset_', to: ['set-in_'] },
    { from: 'set-equality', to: ['subset_'] },
    { from: 'setminus', to: ['set-in_'] },
    { from: 'pair', to: ['nothing_'] },
    { from: 'function', to: ['times-rel'] },
    { from: 'family', to: ['function'] },
    { from: 'cap-cup', to: ['family'] },
    { from: 'field-ax', to: ['function'] },
    { from: 'order-ax', to: ['field-ax'] },
    { from: 'intervals', to: ['order-ax'] },
    { from: 'ordinals', to: ['nothing_'] },
    { from: 'archimed-ax', to: ['order-ax', 'ordinals'] },
    { from: 'cantor-ax', to: ['cap-cup', 'intervals'] },
    { from: 'r', to: ['archimed-ax', 'cantor-ax'] },
    { from: 'abs', to: ['r'] },
    { from: 'inductive-set', to: ['r'] },
    { from: 'n', to: ['inductive-set'] },
    { from: 'sequence', to: ['n'] },
    { from: 'z-q', to: ['n'] },
    { from: 'times-rel', to: ['subset_', 'pair'] },
    { from: 'bounds', to: ['abs'] },
    { from: 'max-min', to: ['r'] },
    { from: 'floor', to: ['r'] }, { from: 'floor', to: ['finite-min'], 'dashes': true },
    { from: 'r-func', to: ['r'] },
    { from: 'img-preimg', to: ['function'] },
    { from: 'inj-surj-bij', to: ['img-preimg'] },
    { from: 'inverse-func', to: ['inj-surj-bij'] },
    { from: 'composition', to: ['inverse-func'] },
    { from: 'equiv-rel', to: ['times-rel'] },
    { from: 'equinum', to: ['inj-surj-bij'] }, { from: 'equinum', to: ['equiv-rel'], 'dashes': true },
    { from: 'count', to: ['n', 'equinum'] },

    { from: 'morgan-laws', to: ['cap-cup', 'setminus', 'set-equality'] },
    { from: 'distr-cap-cup', to: ['cap-cup'] },
    { from: 'math-induct', to: ['sequence'] },
    { from: 'binomial-th', to: ['z-q'] }, { from: 'binomial-th', to: ['math-induct'], 'dashes': true },
    { from: 'finite-min', to: ['max-min'] }, { from: 'finite-min', to: ['math-induct'], 'dashes': true },
    { from: 'q-dense', to: ['z-q'] }, { from: 'q-dense', to: ['archimed-ax', 'floor'], 'dashes': true },
    { from: 'ex-count-sub', to: ['count'] },
    { from: 'inf-sub-count', to: ['count'] },
    { from: 'count-union', to: ['count'] },
    { from: 'q-count', to: ['z-q'] }, { from: 'q-count', to: ['count-union'], 'dashes': true },
    { from: 'r-continuum', to: ['count'] }, { from: 'r-continuum', to: ['cantor-ax'], 'dashes': true }
  ],
  articles: {
    'set-in_': [
      'Понятие множества будет для нас первичным, неопределяемым',
      'Вместо слова \"множество\" часто употребляются его синонимы: класс, совокупность, набор',
      'Множество состоит из объектов, вещей, называемых его элементами',
      'Запись $(x \\in X)$ означает, что объект $(x)$ принадлежит множеству $(X)$, является элементом множества $(X)$',
    ],
    'nothing_': [
      'Множество, в котором нет ни одного элемента, называется пустым и обозначается символом $(\\varnothing)$',
    ],
    'subset_': [
      '$(A \\subset B \\xLeftrightarrow{def} \\forall x \\in A \\Rightarrow x \\in B)$',
    ],
    'setminus': [
      '$(A \\setminus B \\coloneqq \\{x: x \\in A \\And x \\notin B\\})$',
    ],
    'set-equality': [
      '$(A = B \\xLeftrightarrow{def} A \\subset B \\And A \\supset B)$',
    ],
    'pair': [
      '$((a, b) \\coloneqq \\{\\{\\{x\\}, \\varnothing\\}, \\{\\{y\\}\\}\\})$',
    ],
    'ordinals': [
      '$(\\mathbb{0} \\coloneqq \\varnothing)$',
      '$(\\mathbb{1} \\coloneqq \\{\\mathbb{0}\\} = \\{\\varnothing\\})$',
      '$(\\mathbb{2} \\coloneqq \\{\\mathbb{1}, \\mathbb{0}\\} = \\{\\{\\varnothing\\}, \\varnothing\\})$',
      '$(\\mathbb{3} \\coloneqq \\{\\mathbb{2}, \\mathbb{1}, \\mathbb{0}\\} = \\{\\{\\{\\varnothing\\}, \\varnothing\\}, \\{\\varnothing\\}, \\varnothing\\})$',
      '$(...)$',
      '$(\\mathbb{X} \\coloneqq \\{\\mathbb{X}_{-1}, \\mathbb{X}_{-2},..., \\mathbb{0}\\})$',
      '',
      'Схема перехода к новому числу: $(\\{\\Box\\} \\longrightarrow \\{\\Box, \\{\\Box\\}\\})$',
      '',
      'Свойства:',
      '1. $(\\mathbb{X} \\in \\mathbb{X}_{+n} \\Leftrightarrow n \\geq 1)$',
      '2. $(\\mathbb{X} \\subset \\mathbb{X}_{+n} \\Leftrightarrow n \\geq 0)$',
    ]
  }
}
